Fina Version/Models/BuyingCart.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Courses_Center.Models
{
    public class BuyingCart
    {

        [ForeignKey("Buyer")]
        public string BuyUserName { get; set; }

        [ForeignKey("Source")]
        public int SId { get; set; }
        public DateTime Date { get; set; }
        public int Count { get; set; }  
        public decimal Total { get; set; }
        public string BankName { get; set; }
        public int VisaNumber { get; set; }
        public bool ISDeleted { get; set; }
        public virtual Buyer Buyer { get; set; }
        public virtual Source Source { get; set; }  
        

    }
}

Fina Version/Controllers/BuyingCartController.cs
using Courses_Center.Models;
using Courses_Center.Services.BuyingCartServices;
using Courses_Center.Services.SourcesService;
using Courses_Center.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Courses_Center.Controllers
{
    [Authorize("Buyer")]
    public class BuyingCartController : Controller
    {
        IBuyingCartService _buyingCartService;
        private readonly ISource _source;
        public BuyingCartController(IBuyingCartService buyingCartService,ISource source)
        {
            _buyingCartService = buyingCartService;
            _source = source;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddToBuyingCart(int Id,decimal price)
        {
             BuyingCart  buyingCart = new BuyingCart();
            buyingCart.BuyUserName = HttpContext.Session.GetString("username");
            if(buyingCart.BuyUserName==null)
              return RedirectToAction(actionName: "Login", controllerName: "Home");
            buyingCart.SId = Id;
            buyingCart.Total = price;
            _buyingCartService.AddBuyingCart(buyingCart);
            HttpContext.Session.SetString("ProCount", _buyingCartService.DisplayBuyingCart(buyingCart.BuyUserName).Count.ToString());
            return Content("ok");
        }
        public IActionResult Display()
        {
            decimal t = 0;
           List<BuyingCartDto> buyingCartDto= new List<BuyingCartDto>();
           var buyingcart = _buyingCartService.DisplayBuyingCart(HttpContext.Session.GetString("username"));
            int c = 1;
            foreach(var item in buyingcart)
            {
                var source = _source.GetOneSource(item.SId);
                buyingCartDto.Add(new BuyingCartDto(
                    )
                {
                    CartId=item.SId,
                    Id=1,
                    Count = item.Count,
                    Price = source.Price,
                    Title = source.Title,
                    Total = source.Price * item.Count
                }) ;
                c++;
                t += source.Price * item.Count;
            }
            ViewBag.total = t;
            return View(buyingCartDto);
        }

        [HttpPost]
        public void UpdateCount(int Id,int Count,decimal Price)
        {
            _buyingCartService.UpdateBuyingCart(Id,Count, Price);
        }

    }
}

Fina Version/Views/BuyingCart/Display.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model IEnumerable<Courses_Center.ViewModels.BuyingCartDto>

 <div class="slider-area ">
    <!-- Mobile Menu -->
    <div class="single-slider slider-height2 d-flex align-items-center" data-background="">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>سلة المشتريات</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <!-- slider Area End-->

  <!--================Cart Area =================-->
@if (Model != null)
{

    <section class="cart_area ">
        <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    
                
              <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="assets/img/arrivel/arrivel_1.png" alt="" />
                    </div>
                    <div class="media-body">
                      <p>@item.Title</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>$@item.Price</h5>
                </td>
                <td>
                  <div class="product_count">
                    <!-- <input type="text" value="1" min="0" max="10" title="Quantity:"
                      class="input-text qty input-number" />
                    <button
                      class="increase input-number-increment items-count" type="button">
                      <i class="ti-angle-up"></i>
                    </button>
                    <button
                      class="reduced input-number-decrement items-count" type="button">
                      <i class="ti-angle-down"></i>
                    </button> -->
                    <span  class="input-number-decrement"> <i onclick="minus(@item.Id,@item.Price,@item.CartId)"   class="ti-minus"></i></span>
                    <input asp-for="@item.Count" id="v'@item.Id'"  class="input-number" type="text" value="@item.Count" min="0" max="1000">
                    <span class="input-number-increment"> <i onclick="changetotal(@item.Id,@item.Price,@item.CartId)"  class="ti-plus"></i></span>
                  </div>
                </td>
                <td>
                  <h5 id="@item.Id">@item.Total</h5>
                </td>
              </tr>
             }
              <tr class="bottom_button">
                <td>
                  <a  class="btn_1" asp-action="" asp-controller="BuyingCart">Update Cart</a>
                </td>
                <td></td>
                <td></td>
                <td>
                  <div class="cupon_text float-right">
                    <a class="btn_1" href="#">Close Coupon</a>
                  </div>
                </td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h5>Subtotal</h5>
                </td>
                <td>
                  <h5 id="total">@ViewBag.total</h5>
                </td>
              </tr>
             
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <a class="btn_1" href="#">Continue Shopping</a>
            <a class="btn_1 checkout_btn_1" href="#">Proceed to checkout</a>
          </div>
        </div>
      </div>
  </section>
  }
  <!--================End Cart Area =================-->
  @section Scripts{
      <script>
          function changetotal(v1,v2,v3){
               let s2 = 'v'+"'" + v1+"'";
         console.log(document.getElementById(s2).value)
              let ii = parseInt(document.getElementById(v1).innerHTML) +v2;
    document.getElementById(v1).innerHTML = ii;
              let t = parseFloat(document.getElementById("total").innerHTML) + v2 ;
              console.log(t)
     document.getElementById("total").innerHTML=t
   $.ajax({
        url: "/BuyingCart/UpdateCount",
       
        type: 'POST',
        data: {Id:v3,Price:v2,Count:parseInt(document.getElementById(s2).value)+1 },// {courses:$("#courses").val(), instructor:$("#instructor").val(), department:$("#department").val(), colleges:$("#colleges").val(), unversity:$("#unversity").val(), Source_Type:$("#Source_Type").val()},             
             success:function(result){
                 console.log(result);
               
             }
          
});
          }
          function minus(v1,v2,v3){
              let s2 = 'v'+"'" + v1+"'";
         console.log(document.getElementById(s2).value)
          let ii = parseInt(document.getElementById(v1).innerHTML) -v2;
    document.getElementById(v1).innerHTML = ii;
     let t = parseFloat(document.getElementById("total").innerHTML) - v2 ;
              console.log(t)
     document.getElementById("total").innerHTML=t
       $.ajax({
        url: "/BuyingCart/UpdateCount",
       
        type: 'POST',
        data: {Id:v3,Price:v2,Count:parseInt(document.getElementById(s2).value)-1 },// {courses:$("#courses").val(), instructor:$("#instructor").val(), department:$("#department").val(), colleges:$("#colleges").val(), unversity:$("#unversity").val(), Source_Type:$("#Source_Type").val()},             
             success:function(result){
                 console.log(result);
               
             }
          
});
          }
      </script>
  }