Fina Version/Controllers/CollageController.cs
//using Aspose.Words;
using Aspose.Words;
using Aspose.Pdf.Devices;
using Courses_Center.Models;
using Courses_Center.Services.College_Service;
using Courses_Center.Services.Course_Service;
using Courses_Center.Services.Department_Service;
using Courses_Center.Services.Professor_Service;
using Courses_Center.Services.SourcesService;
using Courses_Center.Services.University_Service;
using Courses_Center.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;
using System.Drawing;
using Aspose.Words.Saving;
using System;
using Microsoft.CodeAnalysis.RulesetToEditorconfig;
using ceTe.DynamicPDF.Rasterizer;
using SautinSoft.Document;
using Courses_Center.Services.BuyingCartServices;

namespace Courses_Center.Controllers
{
    
    public class CollageController : Controller
    {
        ICollegeService _CollegeService;
        IUniversityService _UniversityService;
        private readonly IDepartmentService _departmentService;
        private readonly ICourseService _courcesService;
        private readonly ISource _source;
        private readonly IProfessorService _profService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        IBuyingCartService _buyingCartService;
        public CollageController(ICollegeService CollegeService, 
            IUniversityService UniversityService,
            IDepartmentService departmentService,
            ISource source, IProfessorService profService , 
            ICourseService courcesService, 
            IWebHostEnvironment webHostEnvironment,
            IBuyingCartService buyingCartService) {
            _CollegeService= CollegeService;
            _UniversityService= UniversityService;
            _departmentService = departmentService;
            _source= source;
            _profService = profService;
            _courcesService = courcesService;
            _webHostEnvironment= webHostEnvironment;
            _buyingCartService= buyingCartService;

        }
        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Index()
        {
            var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
            ViewData["Universities"] = universtyItems;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult DisplayCollage(int? UniverstyID)
        {
            //Modelfilter.CollageID = null;
            if (UniverstyID is null || UniverstyID <= 0 )
                return PartialView("DisplayCollage",null);
            return PartialView("DisplayCollage", _CollegeService.filterCollegesByUni(UniverstyID).ToList());
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Add()
        {
            var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
            ViewData["Universities"] = universtyItems;
            return View();
        }
        [HttpPost]
        public IActionResult AddCollage(College newCollage)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Add));
            try
            {
                _CollegeService.Add(newCollage);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Add));
            }
        }
        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Edit(int? id)
        {
            if (id <= 0 || id == null)
                return NoContent();
            //return RedirectToAction(nameof(Index));
            var res = _CollegeService.GetColWithUniversty(id);
            if (res == null)
                return RedirectToAction(nameof(Index));
            var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
            ViewData["Universities"] = universtyItems;
            return View(res);
        }
        [HttpPost]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult EditCollage(int? id, College updateCollage)
        {
            if (!ModelState.IsValid || id <= 0 || id == null)
                return RedirectToAction(nameof(Edit));
            try
            {
                var old = _CollegeService.GetColWithUniversty(id);
                if (old == null)
                    return View(nameof(Index));
                var ok = _CollegeService.updateCollage(old, updateCollage);
                if (ok)
                {
                    //var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
                    //ViewData["Universities"] = universtyItems;
                    //return View(nameof(Index));
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch
            {
                return RedirectToAction(nameof(Edit));
            }
        }
        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Delete(int? id)
        {
            var depart = _CollegeService.Get((int)id);
            if (depart == null)
                return NoContent();
            _CollegeService.Remove(depart);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult CheckNameColl(string Name,int UniID)
       {
            bool res = _CollegeService.CheckNameColl(Name,UniID);
            return Json(!res);

        }
        List<Department> departments = new List<Department>();
        List<Course> CoursesList=new List<Course>();
        
        public IActionResult CollegeDepts(int Id)
        {
            try
            {
                ViewBag.NameCol = _UniversityService.Get(Id)?.Name;
            }
            catch { }
            departments = _departmentService.getallDepartments(Id);
            ViewBag.departments = new SelectList(departments, "Id", "Name"); ;
            return View();
        }
        [HttpPost]
        
        public async Task<List<Tuple<int, string>>> Courses(int Id)
        {
            CoursesList = _courcesService.getallCources(Id);
            List<string> names = CoursesList.Select(x => x.Name).ToList();
            List<int> Ids = CoursesList.Select(x => x.Id).ToList();
            List<Tuple<int, string>> mylist = new List<Tuple<int, string>>();
            //   mylist.Add(new Tuple<int, string>() { Id, names });
            for (int i = 0; i < names.Count; i++)
            {
                mylist.Add(new Tuple<int, string>(Ids[i], names[i]));
            }
            return mylist;
        }

      
        [HttpPost]
       
        public async Task<List<SourceDto>> Details(int Id)
        {
            
            
            List<Source> x = _source.getallSource(Id);
            
           List<SourceDto> sourceDtos = new List<SourceDto>();

            foreach (var item in x)
            {
                SourceDto sd = new SourceDto();



                //sd.ProfName = _profService.GetOneProfessor(item.ProfID).Name;
                sd.Price = item.Price;
               var user= HttpContext.Session.GetString("username");
                var buy="";
                if (user != null)
                {
                    var buying = _buyingCartService.DisplayFinishBuyingCart(user, item.Id);


                    if(buying.Count >0)
                    sd.Url = "/resources/" + item.Url;
                }
                sd.Title = item.Title;
                sd.Id = item.Id;
                sd.ImageName = item.image;
                var profName = _profService.Get(item.ProfID);
                sd.profName = profName.Name;
                sourceDtos.Add(sd);
                


            }




               return sourceDtos;
        }
        [HttpGet]
        
        public IActionResult product(int Id)
        {


            Source x = _source.GetOneSource(Id);
            //    _source.getallSource(courses, instructor, department, colleges, unversity);
            //   universities = _universityService.getallUniversies();

            List<SourceDto> sourceDtos = new List<SourceDto>();

            SourceDto sd = new SourceDto();
           // sd.ProfName = _profService.GetOneProfessor(x.ProfID).Name;
            sd.Price = x.Price;
            sd.Url = x.Url;
            sd.Title = x.Title;
            sd.Id = x.Id;
            sd.Description = x.Description;

            return View(sd);
        }

    }
}

Fina Version/Views/Collage/Add.cshtml
@model College
<section class="section " style="margin:50px ;">
    <div class=" p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">

        <h1 class="d-flex justify-content-center"> اضافة الكلية </h1>
        <form asp-action="AddCollage" asp-controller="Collage" method="post" enctype="multipart/form-data">
            <div class="row mb-3" bis_skin_checked="1">
                <label class="col-sm-1 col-form-label">الجامعه</label>
                <div class="col-3" bis_skin_checked="1">
                    @if (ViewBag.Universities != null)
                    {
                        <select asp-for="UniID" class="form-select"
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name"))"
                            aria-label="Default select example"
                            value="UniID">
                            <option value="">اختار الجامعة</option>

                        </select>
                        <span asp-validation-for="UniID" class="text-danger"></span>

                    }
                    else
                    {
                        <select asp-for="UniID" class="form-select"
                            aria-label="Default select example"
                            value="UniID">
                            <option value="">لا توجد بيانات</option>
                        </select>
                        <span asp-validation-for="UniID" class="text-danger"></span>

                    }
                </div>
                <label class="col-sm-1 col-form-label">اسم الكليه   </label>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="Name" class="form-control" type="text" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="ISDeleted" value="False" class="form-control" hidden type="text" />
                </div>
                <br>
                <br>
                <br>
                <div class="col-12 d-flex justify-content-center" bis_skin_checked="1">
                    <button class="btn btn-primary" type="submit">  اضافه كليه </button>
                </div>
            </div>
        </form>
    </div>
</section>
@section Scripts
{
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}

Fina Version/Views/Collage/DisplayCollage.cshtml
@model IEnumerable<College>

@if (Model != null)
{

    <div class=" p-3 rounded-3"
     style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">

        <section>
            <table class="table table-striped">

                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th></th>
                    </tr>

                </thead>

                <tbody>
                    @if(Model.Count()>0){
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="Collage" asp-route-id="@item.Id">
                                    <i class='bx bx-edit-alt' style="cursor: pointer;"></i>
                                </a>

                                <a asp-action="Delete" asp-controller="Collage" asp-route-id="@item.Id" onclick="return confirm('هل انت متأكد من حذف @item.Name')">
                                    <i class='bx bx-x' style="cursor: pointer;"></i>
                                </a>
                            </td>
                        </tr>
                    }
                    }
                    else{
                        <tr>
                            <td>
                        <section>
                            <p class="text-info h2 text-center">
                                لا توجد اى اقسام
                            </p>
                        </section>
                            </td>
                            <td></td>
                        </tr>
                    }

                </tbody>
            </table>
        </section>
    </div>
}

Fina Version/Views/Collage/Edit.cshtml
@model College
<section class="section " style="margin:50px ;">
    <div class=" p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">

        <h1 class="d-flex justify-content-center"> تعديل الكلية </h1>
        <form asp-action="EditCollage" asp-controller="Collage" method="post" enctype="multipart/form-data">
            <input hidden name="id" id="id" value="@Model.Id"/>
            <div class="row mb-3" bis_skin_checked="1">
                <label class="col-sm-1 col-form-label">الجامعه</label>
                <div class="col-3" bis_skin_checked="1">
                    @if (ViewBag.Universities != null)
                    {
                        <select asp-for="UniID"  class="form-select" 
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name",Model.University.Id))"
                            aria-label="Default select example"
                            value="UniID">
                        </select>
                        <span asp-validation-for="UniID" class="text-danger"></span>

                    }
                    else
                    {
                        <select asp-for="UniID"  class="form-select" 
                            aria-label="Default select example"
                            value="UniID">
                            <option value="" >لا توجد بيانات</option>
                        </select>
                        <span asp-validation-for="UniID" class="text-danger"></span>

                    }
                </div>
                <label class="col-sm-1 col-form-label">اسم الكليه   </label>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="Name" class="form-control" type="text" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="ISDeleted" value="False" class="form-control" hidden type="text" />
                </div>
                <br>
                <br>
                <br>
                <div class="col-12 d-flex justify-content-center" bis_skin_checked="1">
                    <button class="btn btn-primary" type="submit">  تعديل كليه </button>
                </div>
            </div>
        </form>
    </div>
</section>

@section Scripts
    {
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
    }

Fina Version/Views/Collage/Index.cshtml
@model FilterDepartViewModel
<section class="section " style="margin:50px ;">

    <div class=" p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">
        <form data-ajax-url="/admin/Collage/DisplayCollage" data-ajax="true" data-ajax-method="post"
              data-ajax-mode="replace" data-ajax-update="#DataCollage"
              data-ajax-begin="OnBegin" data-ajax-failure="OnFailure"
              data-ajax-success="OnSuccess" data-ajax-complete="OnComplete">

            <div class="row mb-3" bis_skin_checked="1">
                <label class="col-sm-1 col-form-label">الجامعه</label>
                <div class="col-3" bis_skin_checked="1">
                    @if (ViewBag.Universities != null)
                    {
                        <select asp-for="UniverstyID" class="form-select" 
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name"))"
                            aria-label="Default select example"
                            value="UniverstyID">
                            <option value="">اختر الجامعه</option>

                        </select>
                    }
                    else
                    {
                        <select asp-for="UniverstyID" class="form-select" 
                            aria-label="Default select example"
                            value="UniverstyID">
                            <option value="">لا توجد بيانات</option>
                        </select>
                    }
                    <span asp-validation-for="UniverstyID"  class="text-danger"></span>

                </div>
                <br />
                <br />

                <div class="col-12 d-flex justify-content-center" bis_skin_checked="1">
                    <button class="btn btn-primary" type="submit">عرض الكليات </button>
                </div>
            </div>
        </form>
    </div>



</section>

<section class="section " style="margin:50px ;" id="DataCollage">
    @{
        Html.RenderPartial("DisplayCollage");
    }
</section>

@section Scripts{
    <script>

        function OnBegin() {
            console.log("i start");

        }
        function OnSuccess() {
            $('#Modal_PMT').modal('hide')
            console.log("i OnSuccess");

        }
        $('#Modal_PMT').on('hidden.bs.modal', function (e) {
            e.target.hidden;
        })
        function OnComplete() {
            console.log("i OnComplete");
            $('#Modal_PMT').modal('hide')
            $('#Modal_PMT').removeClass('show')

            $('div').remove('.modal-backdrop')

        }

        function OnFailure() {
            console.log("i OnFailure");
            $('#Modal_PMT').modal('hide')

        }
    </script>
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}

Fina Version/Views/Collage/product.cshtml
@model Courses_Center.ViewModels.SourceDto

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
@{
     <!-- slider Area Start-->
    <div class="container py-5">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>تفصيل الملخص</h2>
          </div>
        </div>
      </div>
    </div>
    <!-- slider Area End-->

    <!--================Single Product Area =================-->
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="single_product_img">
                    <embed id="previewImg" src="~/resources/@Model.Url#toolbar=0" width="100%" height="600px" />
          </div>
        </div>
        <div class="col-lg-8 py-3">
          <div class="single_product_text text-center">
            <h3>@Model.Title </h3>
          @*  <h5>@Model.ProfName </h5>*@
            <p>
             @Model.Description
            </p>
            <h3>السعر : @Model.Price</h3>
            <div class="add_to_cart d-inline-block py-3">
              <a
                href="#"
                class="genric-btn danger-border radius justify-content-center"
              >
                اضافة لسلة المشتريات</a
              >
            </div>
            <div class="card_area"></div>
          </div>
        </div>
      </div>
    </div>


}