Fina Version/Models/Source.cs
using Courses_Center.Models.Entity;
using System.ComponentModel.DataAnnotations.Schema;

namespace Courses_Center.Models
{
    public class Source
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
        public string Notes { get; set; }
        public int? CountOfBuy { get; set; }
        public bool ISDeleted { get; set; } = false;
        public string image { get; set; }
      [ForeignKey("Professor")]
        public int ProfID { get; set; }
        public virtual Professor Professor { get; set; }
      

        [ForeignKey("Course")]
        public int CrsID { get; set; }
        public virtual Course Course { get; set; }

        //[ForeignKey("Department")]
        //public int DeptID { get; set; }
        //public virtual Department Department { get; set; }
        public virtual ICollection<BuyingCart> BuyingCarts { get; set; } = new HashSet<BuyingCart>();




    }
}

Fina Version/Controllers/HomeController.cs
using Courses_Center.Models;
using Courses_Center.Services.BuyerService;
using Courses_Center.Services.SourcesService;
using Courses_Center.Services.University_Service;
using Courses_Center.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Courses_Center.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUniversityService _universityService;
        private readonly IBuyerService _buyerServices;
        private readonly ISource _source;

        public HomeController(
            IUniversityService universityService
            , IBuyerService buyerService 
            , ISource source)
        {
            _universityService = universityService;
            _buyerServices = buyerService;
            _source = source;
        }

        // GET: UniversitiesController
        public ActionResult Index()
        {

            ViewBag.uni1 = _universityService.getallUniversies().Take(3).ToList();
            ViewBag.Uni2 = _universityService.getallUniversies().Skip(3).Take(3).ToList();
            ViewBag.Uni3 = _universityService.getallUniversies().Skip(6).Take(3).ToList();
            return View();
        }

        [Authorize]
        public IActionResult Profile()
        {
            var claims = User.Claims.ToList();
            var username = claims[0].Value;
            var password = claims[1].Value;
            if (claims[3].Value == "Admin"|| claims[3].Value == "Owner")
            {
                return NoContent();
            }
            var user = _buyerServices.getOneBuyer(username, password);
            return View(user);
        }
        [Authorize]
        public IActionResult ProfileInfo()
        {
            var claims = User.Claims.ToList();
            var username = claims[0].Value;
            var password = claims[1].Value;

            var user = _buyerServices.getOneBuyer(username, password);

            return PartialView(user);
        }
        [Authorize]
        public IActionResult UpdateProfile()
        {
            var claims = User.Claims.ToList();
            var username = claims[0].Value;
            var password = claims[1].Value;
            if (claims[3].Value == "Admin" || claims[3].Value == "Owner")
            {
                return NoContent();
            }
            ViewData["BuyerOld"] = _buyerServices.getOneBuyer(username, password);
            return View("UpdateProfile");
        }
        [Authorize]
        [HttpPost]
        public IActionResult UpdateProfile(UProfileViewModel model, string UserName, string Password)
        {
            if (ModelState.IsValid)
            {

                var user = _buyerServices.getOneBuyer(UserName, Password);
                if (user == null)
                    return RedirectToAction(nameof(Profile));
                _buyerServices.UpdateDataProfile(user, model);
            }
            return RedirectToAction(nameof(Profile));
        }

        [Authorize]
        public IActionResult ChangePassword()
        {
            var claims = User.Claims.ToList();
            if (claims[3].Value == "Admin" || claims[3].Value == "Owner")
            {
                return NoContent();
            }
            return View("ChangePassword");
        }

        [HttpPost]

        public IActionResult ChangePassword(ChangePassViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("ChangePassword");
            }
            else
            {
                var claims = User.Claims.ToList();
                var username = claims[0].Value;
                var password = claims[1].Value;
                var user = _buyerServices.getOneBuyer(username, password);
                if (user == null || user?.Password != model.OldPassword)
                    return NoContent();
                _buyerServices.ChangePassword(user, model);
                return RedirectToAction("Logout", "Login");

            }
        }
        public IActionResult Sources()
        {
            var claims = User.Claims.ToList();
            var username = claims[0].Value;
            var Sources = _source.getallSourceForBuyer(username).ToList();
            return View(Sources);
        }
        
    }
}

Fina Version/Controllers/SourceController.cs
using Courses_Center.Models;
using Courses_Center.Services.College_Service;
using Courses_Center.Services.Course_Service;
using Courses_Center.Services.CourseProfessorService;
using Courses_Center.Services.Department_Service;
using Courses_Center.Services.Professor_Service;
using Courses_Center.Services.SourcesService;
using Courses_Center.Services.University_Service;
using Courses_Center.ViewModels;

using Courses_Center.ViewModels.Extentsion;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Courses_Center.Controllers
{
   
    public class SourceController : Controller
    {

        private readonly IUniversityService _universityService;
        private readonly ICollegeService _collegeServices;
        private readonly IDepartmentService _departmentService;
        private readonly ICourseService _courcesService;
        private readonly IProfessorService _profService;
        private readonly ISource _source;
        private readonly ICourseProfessorService _courseProfessorService;

        private readonly IWebHostEnvironment _webHostEnvironment;
        public SourceController(IUniversityService universityService,
                    ICollegeService collegeServices,
                    IDepartmentService departmentService, 
                    ICourseService courcesService, 
                    IProfessorService profService, 
                    ISource source, 
                    IWebHostEnvironment webHostEnvironment,
                    ICourseProfessorService courseProfessorService
            )
        {
            _universityService = universityService;
            _collegeServices = collegeServices;
            _departmentService = departmentService;
            _courcesService = courcesService;
            _profService = profService;
            _source = source;
            _webHostEnvironment = webHostEnvironment;
            _courseProfessorService = courseProfessorService;
        }

        List<University> universities;
        List<College> Colleges;
        List<Department> departmentsList;
        List<Course> CoursesList;
        List<Professor> prodList;
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Index()
        {

            universities = _universityService.GetAll().ToList();




            ViewBag.universities = new SelectList(universities, "Id", "Name");

            return View();
        }
        //public void unversity(int Id)
        //{
        //    Colleges = _collegeServices.getallCollege(Id);
        //    ViewBag.colleges = new SelectList(Colleges, "Id", "Name");

        //}


        [HttpPost]
        public async Task<List<Tuple<int, string>>> unversity(int Id)
        {

            Colleges = _collegeServices.filterCollegesByUni(Id).ToList();
            List<string> names = Colleges.Select(x => x.Name).ToList();
            List<int> Ids = Colleges.Select(x => x.Id).ToList();
            List<Tuple<int, string>> mylist = new List<Tuple<int, string>>();
            //   mylist.Add(new Tuple<int, string>() { Id, names });
            for (int i = 0; i < names.Count; i++)
            {
                mylist.Add(new Tuple<int, string>(Ids[i], names[i]));
            }
            return mylist;
        }
        [HttpPost]
        public async Task<List<Tuple<int, string>>> departments(int Id)
        {
            FilterDepartViewModel filterDepartViewModel = new FilterDepartViewModel();
           
            departmentsList = _departmentService.getallDepartments(Id);
            List<string> names = departmentsList.Select(x => x.Name).ToList();
            List<int> Ids = departmentsList.Select(x => x.Id).ToList();
            List<Tuple<int, string>> mylist = new List<Tuple<int, string>>();
            //   mylist.Add(new Tuple<int, string>() { Id, names });
            for (int i = 0; i < names.Count; i++)
            {
                mylist.Add(new Tuple<int, string>(Ids[i], names[i]));
            }
            return mylist;

        }
        [HttpPost]
        public async Task<List<Tuple<int, string>>> courses(int Id)
        {
            CoursesList = _courcesService.getallCources(Id);
            List<string> names = CoursesList.Select(x => x.Name).ToList();
            List<int> Ids = CoursesList.Select(x => x.Id).ToList();
            List<Tuple<int, string>> mylist = new List<Tuple<int, string>>();
            //   mylist.Add(new Tuple<int, string>() { Id, names });
            for (int i = 0; i < names.Count; i++)
            {
                mylist.Add(new Tuple<int, string>(Ids[i], names[i]));
            }
            return mylist;
        }
        [HttpPost]
        public async Task<List<Tuple<int, string>>> Profs(int Id)
        {
            var crsProf = _courseProfessorService.GetAll().Where(A => A.CrsId == Id).ToList();
            var Profess = new List<Professor>();
            foreach (var item in crsProf)
            {
                Profess.Add(_profService.Get(item.ProfId));
            }
            List<string> names = Profess.Select(x => x.Name).ToList();
            List<int> Ids = Profess.Select(x => x.Id).ToList();

            List<Tuple<int, string>> mylist = new List<Tuple<int, string>>();
            //   mylist.Add(new Tuple<int, string>() { Id, names });
            for (int i = 0; i < names.Count; i++)
            {
                mylist.Add(new Tuple<int, string>(Ids[i], names[i]));
            }
            // ViewBag["Id"] = Id;
            return mylist;
        }
        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Add()
        {
            universities = _universityService.GetAll().ToList();
            ViewBag.universities = new SelectList(universities, "Id", "Name");
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Add(SourceDto sourceDto, IFormFile sources)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index");
            _source.AddSource(sourceDto, sources);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Details(SourceDisplayDTO sourceDisplayDTO)
        {
            if(!ModelState.IsValid)
                return RedirectToAction("Index");
            var source = _source.getallSource(sourceDisplayDTO);
            SourceDto sourceDto = new SourceDto();
            ListSourceDto listSourceDto = new ListSourceDto();
            listSourceDto.Sources = source;
            listSourceDto.SourceDisplay=sourceDisplayDTO;

            return PartialView("SourceDisplay", listSourceDto);
        
            //    _source.getallSource(courses, instructor, department, colleges, unversity);
            //   universities = _universityService.getallUniversies();

        }
        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Delete(int Id)
        {
            if(Id == 0)
                return RedirectToAction("Index");
            _source.removeSource(Id);

            return PartialView("SourceDisplay", _source.GetAll());

        }
        [HttpGet]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Update(int Id, int department, int colleges, int unversity)
        {
            
            Source source = _source.GetOneSource(Id);
            SourceDto sourceDto = source.SourceToDTO();
            var cource = _courcesService.GetOneCourse(source.CrsID);
            var prof = _profService.GetOneProfessor(source.ProfID);
            var dept = _departmentService.GetOneDepart(department);
            var college = _collegeServices.GetColWithUniversty(colleges);
            var uni = _universityService.Get(unversity);
            sourceDto.deptId = department;

            sourceDto.uniId = unversity;

            sourceDto.colliId = colleges;

            sourceDto.uniName = uni.Name;
            sourceDto.collName = college.Name;
            sourceDto.deptName = dept.Name;
            var allcolleges = _collegeServices.filterCollegesByUni(unversity).ToList();
            var allDepts = _departmentService.getallDepartments(colleges);
            var allCources = _courcesService.getallCources(department);
            var crsProf = _courseProfessorService.GetAll().Where(P => P.CrsId == source.CrsID).ToList();
            var allprof = _profService.GetAll().Where(P => P.Id == crsProf[0].ProfId);
            var allUni = _universityService.GetAll().ToList();

            var allType = new[] { new { Name = "ملخص" }, new { Name = "حل تاسك" } };
            ViewBag.universities = new SelectList(allUni, "Id", "Name", unversity);
            ViewBag.Colleges = new SelectList(allcolleges, "Id", "Name", college);
            ViewBag.Departments = new SelectList(allDepts, "Id", "Name", department);
            ViewBag.Cources = new SelectList(allCources, "Id", "Name", source.CrsID);
            ViewBag.Profs = new SelectList(allprof, "Id", "Name", source.ProfID);
            ViewBag.Types = new SelectList(allType, "Name", "Name", source.Type);
            return View(sourceDto);
        }
        [HttpPost]
        [Authorize(Roles = "Admin,Owner")]
        public IActionResult Update(SourceDto sourceDto, IFormFile sources)
        {

        
            _source.Update(sourceDto,  sources);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "Admin , Buyer")]
        public IActionResult DisplayOne(int Id)
        {
            return View();
        }

    }
}

Fina Version/Views/Home/ChangePassword.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model ChangePassViewModel

<div class="container " dir="rtl">
    <div class="row justify-content-center">
        <div class="col-12">
            <h1 class="text-center text-danger my-5">تغيير الرقم السرى</h1>
        </div>
        <div class=" col-8  col-md-6 text-right ">
            <form asp-action="ChangePassword"
                  asp-controller="Home"
                  method="post"
                  novalidate="novalidate">
                <div class="form-group my-4">
                    <label asp-for="OldPassword" class="my-2">الرقم السرى القديم</label>
                    <input type="password" style="line-height:2"
                           class="form-control text-right w-100"
                           asp-for="OldPassword"
                           placeholder="الرقم السرى القديم" />
                    <span asp-validation-for="OldPassword" class="text-danger"></span>
                </div>
                <div class="form-group my-4">
                    <label asp-for="NewPassword" class="my-2">كلمة سر جديدة </label>
                    <input type="password" style="line-height:2"
                           class="form-control text-right w-100"
                           asp-for="NewPassword"
                           placeholder="كلمة سر جديدة" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>
                <div class="form-group my-4">
                    <label asp-for="ConfirmPassword" class="my-2">تاكيد كلمة السر</label>
                    <input type="password"
                           class="form-control text-right"
                           asp-for="ConfirmPassword"
                           placeholder="تاكيد كلمة السر" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>

                <button type="submit" value="submit" class="btn_3 w-100">
                    تعديل البيانات
                </button>
            </form>
            <div class="text-center mt-2">
                <a asp-action="Profile" class="text-primary h4" asp-controller="Home">الرجوع الى الملف الشخصى</a>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

Fina Version/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model IEnumerable<Courses_Center.Models.University>


<!-- Universitets-Section -->
<main>
    <div class="slider-area">
        <div class="slider-active">
            <div class="single-slider slider-height"
                 data-background="https://cdn.pixabay.com/photo/2017/12/22/08/01/book-3033196_960_720.jpg">
                <div class="container">
                    <div class="row d-flex align-items-center justify-content-between">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 d-none d-md-block"></div>
                        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-8">
                            <div class="hero__caption">
                                <br />
                                <br />
                                <span data-animation="fadeInRight"
                                      data-delay=".4s"
                                      style="color: red">متعة التعلم</span>
                                <h1 data-animation="fadeInRight" data-delay=".6s">
                                    منصه <br />
                                    المنهج
                                </h1>
                                <br />
                                <div class="hero__btn"
                                     data-animation="fadeInRight"
                                     data-delay="1s">
                                    <a asp-action="NewUser"
                                       asp-controller="Registeration"
                                       class="genric-btn danger e-large">
                                        انشاء حساب جديد
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="pt-5 pb-5 my-4">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h1>الجامعات</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-6"></div>
                <div class="col-6 text-right py-3">
                    <a class="genric-btn danger-border radius"
                       href="#carouselExampleIndicators2"
                       role="button"
                       data-slide="prev">
                        <i class="fa fa-arrow-left"></i>
                    </a>
                    <a class="genric-btn danger-border radius"
                       href="#carouselExampleIndicators2"
                       role="button"
                       data-slide="next">
                        <i class="fa fa-arrow-right"></i>
                    </a>
                </div>
                <div class="col-12">
                    <div id="carouselExampleIndicators2"
                         class="carousel slide"
                         data-ride="carousel">
                        <div class="carousel-inner">
                            @if(ViewBag?.uni1 != null){

                            <div class="carousel-item active">
                                <div class="row">
                                    @foreach (var item in ViewBag.uni1 as IEnumerable<University>)
                                    {
                                        <div class="col-md-4 mb-3">
                                            <div class="card text-center">
                                                <div class="card-body">
                                                    <h4 class="card-title text-center">
                                                        @item.Name
                                                    </h4>
                                                    <a asp-controller="University" asp-action="Details" asp-route-Id="@item.Id"
                                                   class="genric-btn danger-border radius">عرض</a>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>

                            </div>
                            }
                            @if(ViewBag?.uni2 != null){

                            <div class="carousel-item">
                                <div class="row">
                                    @foreach (var item in ViewBag.Uni2 as IEnumerable<University>)
                                    {
                                            <div class="col-md-4 mb-3">
                                                <div class="card text-center">
                                                    <div class="card-body">
                                                        <h4 class="card-title text-center">
                                                            @item.Name
                                                        </h4>
                                                        <a asp-controller="University" asp-action="Details" asp-route-Id="@item.Id"
                                                   class="genric-btn danger-border radius">عرض</a>
                                                    </div>
                                                </div>
                                            </div>
                                    }
                                </div>
                            </div>
                            }
                            @if(ViewBag?.uni3 != null){

                            <div class="carousel-item">
                                <div class="row">
                                    @foreach (var item in ViewBag.Uni3 as IEnumerable<University>)
                                    {
                                            <div class="col-md-4 mb-3">
                                                <div class="card text-center">
                                                    <div class="card-body">
                                                        <h4 class="card-title text-center">
                                                            @item.Name
                                                        </h4>
                                                        <a asp-controller="University" asp-action="Details" asp-route-Id="@item.Id"
                                                   class="genric-btn danger-border radius">عرض</a>
                                                    </div>
                                                </div>
                                            </div>
                                    }
                                </div>
                            </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="text-center py-3">
                <a class="genric-btn danger e-large" asp-controller="University" asp-action="Universities">الجامعات</a>
            </div>
        </div>
    </section>
</main>

Fina Version/Views/Home/Profile.cshtml
@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model Buyer
<style>

    /**********************************/
    /********* My Account CSS *********/
    /**********************************/
    .my-account {
        position: relative;
        padding: 30px 0;
    }

    .my-account .nav.nav-pills .nav-link {
        padding: 10px 15px;
        color: #353535;
        background: #ffffff;
        border-radius: 0;
        border-bottom: 1px solid #dddddd;
        transition: all .3s;
    }

    .my-account .nav.nav-pills .nav-link:last-child {
        border-bottom: none;
    }

    .my-account .nav.nav-pills .nav-link:hover,
    .my-account .nav.nav-pills .nav-link.active {
        color: #ffffff;
        background: #FF6F61;
    }

    .my-account .nav.nav-pills .nav-link i {
        margin-right: 5px;
    }

    .my-account .tab-content {
        padding: 30px;
        background: #ffffff;
    }

    .my-account .tab-content .table {
        width: 100%;
        text-align: center;
        margin-bottom: 0;
    }

    .my-account .tab-content .table .thead-dark th {
        text-align: center;
        color: #353535;
        background: #ffffff;
        border-color: #dddddd;
        border-bottom: none;
        vertical-align: middle;
    }

    .my-account .tab-content .table td {
        vertical-align: middle;
    }

</style>
<div class="my-account" dir="rtl">
    <div class="container-fluid">
        <div class="row justify-content-around">
            <div style="background-color:#f5f5f5" class="card h-100  col-md-3 m-1 text-right shadow-lg p-2 mb-5 bg-white rounded">
                <div class="card-body text-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                         class="rounded-circle img-fluid" style="width: 150px;">
                    <h5 class="my-3">@Model?.UserName</h5>
                    <p class="text-muted mb-1">@Model?.Email</p>
                </div>

                <div class="card-body nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
                    <a class="nav-link h4 active" id="dashboard-nav" data-toggle="pill" href="#dashboard-tab" role="tab" aria-selected="true" onclick="ShowProfileInfo();"><i class="fa fa-tachometer-alt p-1 m-1 h4"></i>الرئيسية</a>
                    <a class="nav-link h4" asp-action="Sources" asp-controller="Home"><i class="fa fa-credit-card p-1 m-1 h4"></i>الكتب</a>
                    <a class="nav-link h4" asp-action="ChangePassword" asp-controller="Home"><i class="fa fa-credit-card p-1 m-1 h4"></i>تغيير الرقم السرى</a>
                    <a class="nav-link h4" aria-selected="false" asp-action="UpdateProfile" asp-controller="Home"><i class="fa fa-user p-1 m-1 h4"></i>تعديل الحساب</a>
                    <a class="nav-link h4" aria-selected="false" asp-action="Logout" asp-controller="Login"><i class="fa fa-sign-out-alt p-1 m-1 h4"></i>تسجيل الخروج</a>
                </div>
            </div>
            <div class="card  col-md-8 m-1 text-right shadow-sm p-2 mb-5 bg-white rounded">
                <div class=" card-body" id="ScreenProfileInfo">
                    <div class="tab-pane fade active show" id="dashboard-tab" role="tabpanel" aria-labelledby="dashboard-nav">
                          @{
                              Html.RenderPartial("ProfileInfo");
                          }
                    </div>
                  
                </div>
                
            </div>
        </div>
    </div>
</div>



@section Scripts
    {
    @{
        Html.Partial("_ValidationScriptsPartial");
    }
    <script>
        
        function ShowProfileInfo() {
            let urlProfileInfo = '@Url.Action("ProfileInfo", "Home")';
            console.log(urlProfileInfo);
            $('#ScreenProfileInfo').load(urlProfileInfo);
        }
        //function UpdateProfileInfo() {
        //    let urlUpdateProfile = '@Url.Action("UpdateProfile", "Home")';
        //    console.log(urlUpdateProfile);
        //    $('#ScreenProfileInfo').load(urlUpdateProfile);
        //}
        //function MySources() {
        //    let urlSources = '@Url.Action("Sources", "Home")';
        //    console.log(urlSources);
        //    $('#ScreenProfileInfo').load(urlSources);
        //}

        //function ChangePass(){
        //    let urlChPass = '@Url.Action("ChangePassword", "Home")';
        //    console.log(urlChPass);
        //    $('#ScreenProfileInfo').load(urlChPass);
        //}
      
    </script>
    }

Fina Version/Views/Home/Sources.cshtml
@{
                Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model IEnumerable<Source>
<h1>asdasdasdasd</h1>
@if (Model != null)
{
    <section class="section " style="margin:50px ;">
        <div class="row ">
            @foreach (var item in Model)
            {
                <div class=" col-4   ">
                    <div class="    p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">
                        <div>
                            <a asp-action="Delete" asp-controller="Source" asp-route-Id="@item.Id" onclick="return confirm('هل انت متاكد من حذف @item.Title ')">
                                <i class='bx bx-x' style="cursor: pointer;"></i>
                            </a>
                            <i class='bx bx-edit-alt' style="cursor: pointer;"></i>
                        </div>
                        <br>
                        <div class=" mb-3" bis_skin_checked="1" width="100%" height="90%">
                            <embed id="previewImg" src="~/resources/@item.Url" width="100%" height="90%" />
                        </div>
                        <div>
                            <h6>@item.Title</h6>
                        </div>
                        <div>
                            <h6>
                                السعر:@item.Price$
                            </h6>
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
}