Fina Version/Models/Department.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Courses_Center.Models
{
    public class Department
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "اسم القسم")]
        [Required(ErrorMessage ="يجب ادخال اسم القسم")]
//        //[RegularExpression("^[^0-9]+$", ErrorMessage = "لا يجب ان يحتوى الحقل على ارقام")]
//<<<<<<< HEAD
//        [Remote("checkDeptname", "Department", ErrorMessage = "هناك قسم بنفس الاسم")]
//=======
//>>>>>>> c76c8111419d8fa4538e6953a76412ac224b8fc7
        public string Name { get; set; }
        [DefaultValue(false)]
        public bool ISDeleted { get; set; }
        [ForeignKey("College")]
        [Required(ErrorMessage = "يجب اختيار الكلية")]
        [RegularExpression("^[1-9]+\\d*$", ErrorMessage = "يجب اختيار الكلية")]
        public int ColID { get; set; }
        public virtual College College { get; set; }

        //[ForeignKey("University")]
        //public int UniID { get; set; }
        //public virtual University University { get; set; }
        public virtual ICollection<Course> Courses { get; set; } = new HashSet<Course>();



    }
}

Fina Version/Controllers/DepartmentController.cs
using Castle.Core.Internal;
using Courses_Center.Models;
using Courses_Center.Services.College_Service;
using Courses_Center.Services.Department_Service;
using Courses_Center.Services.University_Service;
using Courses_Center.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;

namespace Courses_Center.Controllers
{
    [Authorize(Roles = "Admin,Owner")]
    public class DepartmentController : Controller
    {
        IDepartmentService _departmentService;
        ICollegeService _CollegeService;
        IUniversityService _UniversityService;
        public DepartmentController(
            ICollegeService CollegeService, IUniversityService UniversityService,
            IDepartmentService DepartmentService)
        {
            _CollegeService = CollegeService;
            _UniversityService = UniversityService;
            _departmentService = DepartmentService;
        }

        [HttpGet]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult Index()
        {
            var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
            ViewData["Universities"] = universtyItems;
            
            //if (universtyItems.Count > 0)
            //{
            //    var collageItems = _CollegeService.filterCollegesByUni(universtyItems[0].Id)?.ToList();
            //    ViewData["collages"] = collageItems;
            //}
            //else
            //    ViewData["collages"] = null;

            return View();
        }

        [HttpGet]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult ChangeUniversty(int? UniverstyID)
        {
            if (UniverstyID is null || UniverstyID <= 0)
                return NoContent();
            var collageItems = _CollegeService.filterCollegesByUni(UniverstyID)?.ToList();
            return Ok(collageItems);
        }

        [HttpPost]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult DisplayDepartment( FilterDepartViewModel Modelfilter)
        {
            //Modelfilter.CollageID = null;
            if (Modelfilter.CollageID is null || Modelfilter.UniverstyID is null
                || Modelfilter.CollageID <= 0 || Modelfilter.UniverstyID <= 0)
            {
                return PartialView(nameof(DisplayDepartment), null);
            }
            return PartialView("DisplayDepartment",_departmentService.FilterDepart(Modelfilter).ToList());
        }
        [HttpGet]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult Add()
        {

            
            var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
            ViewData["Universities"] = universtyItems;
            if (universtyItems.Count > 0)
            {
                var collageItems = _CollegeService.filterCollegesByUni(universtyItems[0].Id)?.ToList();
                ViewData["collages"] = collageItems;
            }
            else
                ViewData["collages"] = null;

            return View();
        }
        [HttpPost]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult AddDepartment(Department newDepartment)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return RedirectToAction(nameof(Add));
                }
                _departmentService.Add(newDepartment);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Add));
            }
        }

        [HttpGet]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult Edit(int id)
        {
            if (id <= 0)
                    return NoContent();
                //return RedirectToAction(nameof(Index));
            var res = _departmentService.GetDeptWithClUni(id);
            if (res == null)
                return RedirectToAction(nameof(Index));
            var universtyItems = _UniversityService.GetUniverstyNotDelete().ToList();
            ViewData["Universities"] = universtyItems;
            var collageItems = _CollegeService.filterCollegesByUni(res.College.University.Id)?.ToList();
            ViewData["collages"] = collageItems;
            return View(res);
        }
        [HttpPost]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult EditDepartment(int id, Department updateDepartment)
        {
            if (!ModelState.IsValid || id <= 0)
            {
               
                return RedirectToAction(nameof(Edit));
            }
            try
            {
               var old = _departmentService.GetDeptWithClUni(id);
                if(old==null)
                    return View(nameof(Index));

                var ok =  _departmentService.updateDepart(old,updateDepartment);
                if (ok)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Edit));
                }
            }
            catch
            {
                return RedirectToAction(nameof(Edit));
            }
        }


        [HttpGet]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult Delete(int? id)
        {
            var depart = _departmentService.Get(id);
            if (depart == null)
                return NoContent();
            _departmentService.Remove(depart);
            return RedirectToAction("Index");
        }
        [HttpGet]
                [Authorize(Roles = "Admin,Owner")]
        public IActionResult checkDeptname(string Name)
        {
            return Json(!_departmentService.checkDepart(Name));
        }
    }
}

Fina Version/Views/Department/Add.cshtml
@model Department
<section class="section " style="margin:50px ;">
    <div class=" p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">

        <h1 class="d-flex justify-content-center">اضافه قسم </h1>
        <form id="FormDepartment" asp-action="AddDepartment" asp-controller="Department" method="post" enctype="multipart/form-data">

            <div class="row mb-3" bis_skin_checked="1">
                <label class="col-sm-1 col-form-label">الجامعه</label>
                <div class="col-3" bis_skin_checked="1">
                    @if (ViewBag.Universities != null)
                    {
                        <select name="UniverstyID" id="UniverstyID" class="form-select"
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name"))"
                            aria-label="Default select example"
                            value="UniverstyID"
                            onchange="changeUniName(this.value)">
                          <option value="">اختر الجامعة</option>

                        </select>
                    }
                    else
                    {
                        <select name="UniverstyID" id="UniverstyID" class="form-select"
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name"))"
                            aria-label="Default select example"
                            value="UniverstyID">
                            <option value="">لا توجد بيانات</option>
                        </select>
                    }
                    <span id="UniverstyIDEror" name="UniverstyIDEror" class="text-danger"></span>
                </div>
                <label class="col-sm-1 col-form-label">الكليه</label>
                <div class="col-3" bis_skin_checked="1" id="Collage_Section">
                   @* @if (ViewBag.collages != null)
                    {
                        <select asp-for="ColID" class="form-select" required
                            value="ColID"
                            asp-items="@(new SelectList(ViewBag.collages,"Id","Name"))"
                            aria-label="Default select example">
                        </select>

                    }
                    else
                    {*@
                    <select asp-for="ColID" class="form-select"
                            aria-label="Default select example"
                            asp-items="@(new SelectList(ViewBag.collages,"Id","Name"))"
                            value="UniID">
                        <option value="">اختار الكلية</option>
                    </select>
                    <span id="MessageErrorColID" asp-validation-for="ColID" class="text-danger"></span>

                    @*}*@

                </div>
                <label class="col-sm-1 col-form-label">اسم القسم   </label>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="Name"  class="form-control" type="text"  />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="ISDeleted" value="False" class="form-control" hidden type="text"  />
                </div>
                <br>
                <br>
                <div class="col-12 d-flex justify-content-center" bis_skin_checked="1">
                    <button class="btn btn-primary" id="submitData" type="submit">  اضافه قسم </button>
                </div>
                </div>
        </form>
    </div>
</section>


@section Scripts{
    <script type="text/javascript">
        function changeUniName(value) {
            if (value == "اختر الجامعة") {
                document.getElementById("ColID").disabled = true;
                $("#ColID").empty();
                $("#ColID").append('<option>اختر الكلية</option>');

            }
            else {
                $.ajax({
                    type: "Get",
                    dataType: "json",
                    Cache: false,
                    url: "/admin/Department/ChangeUniversty",
                    data: { "UniverstyID": value },
                    success: function (response) {
                   

                        if ((response + '').length == 0) {
                            console.log("no data")
                            $("#ColID").append('<option value="">لا توجد بيانات</option>');
                            $("#MessageErrorColID").append('<span id="ColID - error" class="" > يجب اختيار الكلية < /span>')
                        }
                        else {
                            $("#ColID").empty();
                            console.log(" data")
                            $("#ColID-error").remove();
                            $.each(response, function (i, state) {


                                $("#ColID").append('<option value="' + state.id + '">' + state.name + '</option>');
                                // here we are adding option for States
                            });
                        }
                        document.getElementById("ColID").disabled = false;

                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            }
          

          


        };
    </script>
 
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}

Fina Version/Views/Department/DisplayDepartment.cshtml
@model IEnumerable<Department>

@if (Model != null)
{

    <div class=" p-3 rounded-3"
     style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">

        <section>
            <table class="table table-striped">

                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th></th>
                    </tr>

                </thead>

                <tbody>
                    @if(Model.Count()>0){
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                    <a  asp-action="Edit" asp-controller="Department" asp-route-id="@item.Id">
                                    <i class='bx bx-edit-alt' style="cursor: pointer;"></i>
                                </a>

                                    <a asp-action="Delete" asp-controller="Department" asp-route-id="@item.Id" onclick="return confirm('هل انت متأكد من حذف @item.Name')">
                                    <i class='bx bx-x' style="cursor: pointer;"></i>
                                </a>
                            </td>
                        </tr>
                    }
                    }
                    else{
                        <tr>
                            <td>
                        <section>
                            <p class="text-info h2 text-center">
                                لا توجد اى اقسام
                            </p>
                        </section>
                            </td>
                            <td></td>
                        </tr>
                    }

                </tbody>
            </table>
        </section>
    </div>
}

Fina Version/Views/Department/Edit.cshtml
@model Department
<section class="section " style="margin:50px ;">
    <div class=" p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">

        <h1 class="d-flex justify-content-center">تعديل قسم </h1>
        <form asp-action="EditDepartment" asp-controller="Department" enctype="multipart/form-data">
            <input hidden name="id" id="id" value="@Model.Id" />
            <input hidden asp-for="Id" />
            <div class="row mb-3" bis_skin_checked="1">

                <label class="col-sm-1 col-form-label">الجامعه</label>
                <div class="col-3" bis_skin_checked="1">
                    @if (ViewBag.Universities != null)
                    {
                        <select name="UniverstyID" id="UniverstyID" class="form-select" required
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name",Model.College.University.Id))"
                            aria-label="Default select example"
                            value="UniverstyID"
                            onchange="changeUniName(this.value)">
                        </select>
                    }
                    else
                    {
                        <select name="UniverstyID" id="UniverstyID" class="form-select" required
                            aria-label="Default select example"
                            value="UniverstyID">
                            <option>لا توجد بيانات</option>
                        </select>
                    }
                    <span asp-validation-for="College.UniID" class="text-danger"></span>
                </div>
                <label class="col-sm-1 col-form-label">الكليه</label>
                <div class="col-3" bis_skin_checked="1" id="Collage_Section">
                    @if (ViewBag.collages != null)
                    {
                        <select asp-for="ColID" class="form-select" required
                            value="ColID"
                            asp-items="@(new SelectList(ViewBag.collages,"Id","Name",Model.ColID))"
                            aria-label="Default select example">
                        </select>

                    }
                    else
                    {
                        <select asp-for="ColID" class="form-select" required
                            value="ColID"
                            aria-label="Default select example">
                            <option value="">لا توجد بيانات</option>
                        </select>
                    }
                    <span asp-validation-for="ColID" class="text-danger"></span>

                </div>
                <label class="col-sm-1 col-form-label">اسم القسم   </label>
                <div class="col-3" bis_skin_checked="1">
                    <input asp-for="Name" value="@Model.Name" required class="form-control" type="text" required />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <br>
                <br>
                <br>
                <div class="col-12 d-flex justify-content-center" bis_skin_checked="1">
                    <button class="btn btn-primary" type="submit">  تعديل قسم </button>
                </div>
            </div>
        </form>
    </div>
</section>


@section Scripts{
    <script type="text/javascript">
        function changeUniName(value) {
            console.log(value);
            $.ajax({
                type: "Get",
                dataType: "json",
                Cache: false,
                url: "/admin/Department/ChangeUniversty",
                data: { "UniverstyID": value },
                success: function (response) {
                    $("#ColID").empty();
                    console.log(response);
                    $.each(response, function (i, state) {
                        console.log(state.name)
                        console.log(state)
                        $("#ColID").append('<option value="' + state.id + '">' + state.name + '</option>');
                        // here we are adding option for States
                    });

                },
                failure: function (response) {
                    console.log(response.responseText);
                },
                error: function (response) {
                    console.log(response.responseText);
                }
            });

        };
    </script>
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
   
}

Fina Version/Views/Department/Index.cshtml
@model FilterDepartViewModel
<section class="section " style="margin:50px ;">

    <div class=" p-3 rounded-3" style="background: #fff; border: 1px solid transparent; box-shadow: 0 2px 5px 1px rgb(64 60 67 / 16%);">
        <form data-ajax-url="/admin/Department/DisplayDepartment" data-ajax="true" data-ajax-method="post"
              data-ajax-mode="replace" data-ajax-update="#DataDepartment"
              data-ajax-begin="OnBegin" data-ajax-failure="OnFailure"
              data-ajax-success="OnSuccess" data-ajax-complete="OnComplete">


            <div class="row mb-3" bis_skin_checked="1">
                <label class="col-sm-1 col-form-label">الجامعه</label>
                <div class="col-3" bis_skin_checked="1">
                    @if (ViewBag.Universities != null)
                    {
                        <select asp-for="UniverstyID" class="form-select"
                            asp-items="@(new SelectList(ViewBag?.Universities,"Id","Name"))"
                            aria-label="Default select example"
                            value="UniverstyID"
                            onchange="changeUniName(this.value)">
                            <option value="">اختر الكلية</option>

                        </select>
                    }
                    else
                    {
                        <select asp-for="UniverstyID" class="form-select"
                            aria-label="Default select example"
                            value="UniverstyID">
                            <option value="">لا توجد بيانات</option>
                        </select>
                    }
                    <span asp-validation-for="UniverstyID" class="text-danger"></span>

                </div>
                <label class="col-sm-1 col-form-label">الكليه</label>
                <div class="col-3" bis_skin_checked="1" id="Collage_Section">
                    @*   @if (ViewBag.collages != null)
                    {
                    <select asp-for="CollageID" class="form-select" disabled
                    value="CollageID"
                    asp-items="@(new SelectList(ViewBag.collages,"Id","Name"))"
                    aria-label="Default select example">
                    </select>

                    }
                    else
                    {*@
                    <select asp-for="CollageID" class="form-select" disabled
                            aria-label="Default select example">
                        <option value="">اختر الكلية</option>
                        @*<option>لا توجد بيانات</option>*@
                    </select>
                    @*}*@
                    <span asp-validation-for="CollageID" class="text-danger"></span>

                </div>
                <br>
                <br>

                <br>

                <div class="col-12 d-flex justify-content-center" bis_skin_checked="1">
                    <button class="btn btn-primary" type="submit">عرض الاقسام </button>
                </div>
            </div>
        </form>
    </div>



</section>
<section class="section " style="margin:50px ;" id="DataDepartment">
    @{
        Html.RenderPartial("DisplayDepartment");
    }
</section>

@section Scripts{
    <script type="text/javascript">
        function changeUniName(value) {
            if (value == "اختر الجامعة") {
                document.getElementById("CollageID").disabled = true;
                $("#CollageID").empty();
                $("#CollageID").append('<option>اختر الكلية</option>');

            }
            else {
                $.ajax({
                    type: "Get",
                    dataType: "json",
                    Cache: false,
                    url: "/admin/Department/ChangeUniversty",
                    data: { "UniverstyID": value },
                    success: function (response) {
                        $("#CollageID").empty();
                        if((response + '').length==0){
                            console.log("no data")
                            $("#CollageID").append('<option>لا توجد بيانات</option>');
                        }
                        else{
                            console.log(" data")
                            $.each(response, function (i, state) {


                                $("#CollageID").append('<option value="' + state.id + '">' + state.name + '</option>');
                                // here we are adding option for States
                            });
                        }
                        document.getElementById("CollageID").disabled = false;

                    },
                    failure: function (response) {
                        console.log(response.responseText);
                    },
                    error: function (response) {
                        console.log(response.responseText);
                    }
                });
            }

        };
    </script>
    <script>

        function OnBegin() {
            console.log("i start");

        }
        function OnSuccess() {
            $('#Modal_PMT').modal('hide')
            console.log("i OnSuccess");

        }
        $('#Modal_PMT').on('hidden.bs.modal', function (e) {
            e.target.hidden;
        })
        function OnComplete() {
            console.log("i OnComplete");
            $('#Modal_PMT').modal('hide')
            $('#Modal_PMT').removeClass('show')

            $('div').remove('.modal-backdrop')

        }

        function OnFailure() {
            console.log("i OnFailure");
            $('#Modal_PMT').modal('hide')

        }
    </script>
    @{
        Html.RenderPartial("_ValidationScriptsPartial");
    }
}